# Generated by Django 5.0.7 on 2024-08-01 03:54

import apps.users.models.student_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academic_register',
            field=models.CharField(max_length=10, unique=True, validators=[apps.users.models.student_model.validate_academic_register], verbose_name='registro acadêmico'),
        ),
    ]
