# Generated by Django 5.0.7 on 2024-08-01 05:10

import apps.users.models.professor_model
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_student_academic_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
                ('siape', models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(7), apps.users.models.professor_model.validate_siape], verbose_name='Sistema Integrado de Administração de Pessoal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('courses', models.ManyToManyField(related_name='professor', to='users.course', verbose_name='cursos')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.department', verbose_name='departamento')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
    ]
