# Generated by Django 5.0.7 on 2024-08-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_professor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='nothing_listed_emmited',
            field=models.BooleanField(default=False, verbose_name='nada consta emitido'),
        ),
    ]
