version: '3.8'

services:
  web:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8000 # gunicorn ./src/inventory.wsgi.application --bind 0.0.0.0:8000
    volumes:
      - ./src/:/usr/src
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inventory
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 20s
      retries: 120
    ports:
      - 5432:5432

volumes:
  postgres_data: