version: '3.8'

services:
  web:
    build: .
    command:  gunicorn --chdir /src/ inventory.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./src/:/usr/src
    ports:
      - 8000:8000
      # - 8080:8080
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inventory
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 20s
      retries: 120
    ports:
      - 5432:5432
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning 
    volumes:
      - cache:/data

volumes:
  postgres_data:
  cache:
    driver: local