# Generated by Django 5.0.7 on 2024-08-01 04:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_studentloan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentloan',
            name='date_of_loan',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='data do empréstimo'),
        ),
    ]
