# Generated by Django 5.0.7 on 2024-08-01 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_studentloan_date_of_loan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='quantity_avaliable',
            new_name='quantity_available',
        ),
    ]
