# Generated by Django 5.0.7 on 2024-08-02 01:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_rename_quantity_avaliable_item_quantity_available'),
        ('users', '0008_professor_nothing_listed_emmited'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='available_for_students',
            field=models.BooleanField(default=True, verbose_name='Disponível para empréstimos de alunos'),
        ),
        migrations.CreateModel(
            name='ProfessorLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantidade')),
                ('date_of_loan', models.DateField(default=django.utils.timezone.now, verbose_name='data do empréstimo')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='data da devolução')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.item', verbose_name='item')),
                ('location', models.ManyToManyField(blank=True, null=True, to='items.location', verbose_name='lugar')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.professor', verbose_name='professor')),
            ],
            options={
                'verbose_name': 'Empréstimo do Professor',
                'verbose_name_plural': 'Empréstimos de Professores',
            },
        ),
    ]
