# Generated by Django 5.0.7 on 2024-08-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_available_for_students_professorloan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorloan',
            name='location',
            field=models.ManyToManyField(blank=True, to='items.location', verbose_name='lugar'),
        ),
    ]
