# Generated by Django 5.0.7 on 2024-08-02 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_professorloan_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentloan',
            options={'verbose_name': 'Empréstimo de Estudante', 'verbose_name_plural': 'Empréstimos de Estudantes'},
        ),
    ]
